@startuml


' Actors
ACTOR 管理员

' Boundaries
BOUNDARY 管理界面

' Controls
CONTROL 修改导师招生名额
CONTROL 修改各年份导师招生资格
CONTROL 修改导师职称
CONTROL 修改导师个人信息
CONTROL 更新每年基础信息
CONTROL 根据当年年份更新导师招生资格

' Entities
ENTITY 导师招生名额信息
ENTITY 导师招生资格信息
ENTITY 导师职称信息
ENTITY 导师个人信息
ENTITY 基础信息
ENTITY 当年年份信息

' Relationships
管理员 --> 管理界面 : "管理界面"
管理界面 --> 修改导师招生名额 : "修改招生名额"
管理界面 --> 修改各年份导师招生资格 : "修改招生资格"
管理界面 --> 修改导师职称 : "修改职称"
管理界面 --> 修改导师个人信息 : "修改个人信息"
管理界面 --> 更新每年基础信息 : "更新基础信息"
管理界面 --> 根据当年年份更新导师招生资格 : "更新招生资格"

修改导师招生名额 --> 导师招生名额信息 : "更新招生名额信息"
修改各年份导师招生资格 --> 导师招生资格信息 : "更新招生资格信息"
修改导师职称 --> 导师职称信息 : "更新职称信息"
修改导师个人信息 --> 导师个人信息 : "更新个人信息"
更新每年基础信息 --> 基础信息 : "更新基础信息"
根据当年年份更新导师招生资格 --> 当年年份信息 : "读取当年年份"
根据当年年份更新导师招生资格 --> 导师招生资格信息 : "更新招生资格信息"

@enduml


